---
title: "dplyr"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
gapminder = read.csv("data/gapminder_data.csv")
```


```{r}
mean(gapminder[gapminder$continent== "Africa", "gdpPercap"])
```


```{r}
mean(gapminder[gapminder$continent== "Asia", "gdpPercap"])
```

```{r}
mean(gapminder[gapminder$continent== "Europe", "gdpPercap"])
```


```{r}
library(dplyr)
```

```{r}
head(gapminder)
```

```{r}
year_country_gdp = select(gapminder, year, country, gdpPercap)
head(year_country_gdp)
```

```{r}
gapminder %>%
  select(year, country, gdpPercap) ->
  year_country_gdp
year_country_gdp
```
 ## Filter

```{r}
gapminder %>%
  filter(continent == "Europe") %>%
  select(year, country, gdpPercap) ->
  year_country_gdp_euro

year_country_gdp_euro
```

## Challenge 1
```{r}
gapminder %>%
  filter(continent == "Africa") %>%
  select(year, country, lifeExp) ->
  year_country_lifeexp_africa

nrow(year_country_lifeexp_africa)
dim(year_country_lifeexp_africa)
year_country_lifeexp_africa
```

## Group_By and SUmmarize
```{r}
str(gapminder)
```


```{r}
gapminder
```

```{r}
gapminder %>%
  group_by(continent)
```
```{r}
gapminder %>%
  group_by(continent) %>%
  str
```

```{r}
gapminder %>%
  group_by(continent) %>%
  summarize(mean_gdpPercap = mean(gdpPercap))
```

```{r}
gapminder %>%
  group_by(country) %>%
  summarize(lifeExp_per_country = mean(lifeExp)) %>%
  arrange(lifeExp_per_country)
```

```{r}
gapminder %>%
  group_by(continent, year) %>%
  summarise(mean_gdpPercap = mean(gdpPercap))
```

```{r}
gapminder %>%
  group_by(continent, year) %>%
  summarise(mean_gdpPercap = mean(gdpPercap),
            sd_gdpPercap = sd(gdpPercap),
            mean_pop = mean(pop), 
            sd_pop= sd(pop))
```

```{r}
gapminder %>%
  filter(year == 2002) %>%
  count(continent, sort = TRUE)
```
```{r}
my_zero = function(x){
  return(0)
}
```


## Using 
```{r}
gapminder %>%
  mutate(gdp_billon = gdpPercap*pop/10^9) %>%
  group_by(continent,year) %>%
  summarise(mean_gdpPercap = mean(gdpPercap),
            sd_gdpPercap = sd(gdpPercap),
            mean_pop = mean(pop),
            sd_pop = sd(pop),
            mean_gdp_billion = mean(gdp_billon),
            sd_gdp_billion = sd(gdp_billon),
            stupid_zero = my_zero(pop)
            )

```

```{r}
gapminder %>%
  mutate(gdp_billon = 
           ifelse(lifeExp > 25, gdpPercap*pop/10^9, NA)) %>%
  group_by(continent,year) %>%
  summarise(mean_gdpPercap = mean(gdpPercap),
            sd_gdpPercap = sd(gdpPercap),
            mean_pop = mean(pop),
            sd_pop = sd(pop),
            mean_gdp_billion = mean(gdp_billon),
            sd_gdp_billion = sd(gdp_billon),
            stupid_zero = my_zero(pop)
            )

```

```{r}
# Get the start letter of each country
starts.with <- substr(gapminder$country, start = 1, stop = 1)
# Filter countries that start with "A" or "Z"
az.countries <- gapminder[starts.with %in% c("A", "Z"), ]
# Make the plot
ggplot(data = az.countries, aes(x = year, y = lifeExp, color = continent)) +
  geom_line() + facet_wrap( ~ country)
```

```{r}
gapminder %>%
  mutate(startsWith = substr(country, start=1, stop=1))
```



```{r}
gapminder %>%
  mutate(startsWith = substr(country, start=1, stop=1)) %>%
  filter(startsWith %in% c("A", "Z")) %>%
  ggplot(aes(x=year, y=lifeExp, color = continent)) +
  geom_line() +
  facet_wrap( ~ country)
```
```{r}
gapminder %>%
  filter(substr(country, start=1, stop=1) %in% c("A", "Z")) %>%
  ggplot(aes(x=year, y=lifeExp, color = continent)) +
  geom_line() +
  facet_wrap( ~ country)
```
