---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
x = c(5.4, 6.2, 7.1, 4.8, 7.5)
names(x) = c('a', 'b', 'c', 'd', 'e')
x
```


```{r}
x[1]
```

```{r}
x[4]
```

```{r}
c(1,3)
```

```{r}
x[c(1,3)]
```
```{r}
1:4
```

```{r}
seq(4)
```
```{r}
seq(1,4)
```

```{r}
x[1:4]
```

```{r}
i = seq(1, 10, by=2)
x[i]
```

```{r}
x[(c(1,2,1))]
```

```{r}
x[0]
```

```{r}
x[-2]
```

```{r}
x[c(-2,-4)]
```

```{r}
x
```

```{r}
x = x[-4]
x
```


```{r}
x["b"]
```

```{r}
x[c("b","e")]
```


```{r}
x[c(FALSE, FALSE, TRUE, FALSE, TRUE)]
```

```{r}
x > 7
```


```{r}
x[x > 7]
```


```{r}
x[names(x)=="a"]
```

```{r}
x > 7
```
```{r}
2 < x & x < 5
```

```{r}
x[2 < x & x < 5]
```


```{r}
2 < x
x < 5
2 < x | x < 5

```

```{r}
x[-"a"]
```

```{r}
x[names(x) != "a"]
```

```{r}
x[names(x) != c("a","c")]
```

```{r}
x = c(5.4, 6.2, 7.1, 4.8, 7.5, 8.3)
names(x) = c('a', 'b', 'c', 'd', 'e', 'f')
x[names(x) != c("a","c")]

```

```{r}
x[! names(x) %in% c("a","c")]

```


```{r}
seAsia <- c("Myanmar","Thailand","Cambodia","Vietnam","Laos")
gapminder = read.csv("data/gapminder_data.csv")

countries = gapminder$country
countries = unique(as.character(gapminder$country))
countries[countries %in% seAsia]
```
```{r}
# gapminder$country %in% seAsia

gapminder[gapminder$country %in% seAsia, ]
```


```{r}
countries[countries %in% seAsia]

```

```{r}
# na.omit

x = c(NA, 1:4, NA)
x
```

```{r}
na.omit(x)
```
```{r}
is.na(x)
```
```{r}
is.finite(10/0)
is.infinite(10/0)
is.nan(NaN)
```

## subsetting data frames
```{r}
head(gapminder)
```

```{r}
gapminder[3]
```

```{r}
head(gapminder[3])
```

```{r}
gapminder["lifeExp"]
```

```{r}
gapminder[["lifeExp"]]
```

```{r}
gapminder[1:3,]
```
```{r}
gapminder[3,]
```
```{r}
gapminder_small = gapminder[c(1:9, 19:23),]
gapminder_small
```

```{r}

```

