---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyr)
gapminder = read.csv("data/gapminder_data.csv")
gapminder
```

```{r}
download.file("https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder_wide.csv",
              destfile = "data/gap_wide.csv")
gap_wide = read.csv("data/gap_wide.csv")
```
```{r}
gap_wide %>% head(2)
```

```{r}
gap_wide %>%
  gather(obstype_year, obs_values, 
         starts_with("pop"),
         starts_with("lifeExp"),
         starts_with("gdpPercap"))
```

```{r}
gap_wide %>%
  gather(obstype_year,
         obs_values,
         -continent,
         -country)
```

```{r}
gap_wide %>%
  gather(obstype_year,
         obs_values,
         -continent,
         -country) %>%
  separate(obstype_year, into = c("obs_type", "year"), sep="_") %>%
  mutate(year = as.integer(year)) ->
  gap_long
  
```


```{r}
gap_long
```
```{r}
gap_long %>%
  spread(obs_type, obs_values)
```

